### ISSUE TITLE
How to test locally?

### ISSUE THREAD

**Issue by cjbottaro** [bitwalker/libcluster#10]
Hi, sorry to ask a question on the issue tracker, but not sure where else to ask.

How can I play around with this locally?  If I use the Epmd strategy, then I can only start up a single Erlang VM and it claims to connect to both hosts in the config (which doesn't make sense to me).

```
$ iex --cookie foo --sname node1 -S mix
11:34:55.841 [info]  [libcluster:example] connected to :node1@haswell
11:34:55.841 [info]  [libcluster:example] connected to :node2@haswell

$ iex --cookie foo --sname node2 -S mix
** (Mix) Could not start application libcluster: Cluster.App.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Strategy.Epmd
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Elixir.ClusterWork.connect/1 is undefined!
```

But really I would like to get the Gossip strategy to work locally.  I created a second ip address on en0 like so:
```
$ ifconfig en0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 60:f8:1d:b3:58:d8
	inet6 fe80::148c:37c9:89e3:157d%en0 prefixlen 64 secured scopeid 0x4
	inet 192.168.1.68 netmask 0xffffff00 broadcast 192.168.1.255
	inet 192.168.1.69 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

And my libcluster config looks like:
```
config :libcluster,
  topologies: [
    gossip_example: [
      strategy: Cluster.Strategy.Gossip,
      config: [
        port: 45892,
        if_addr: {192,168,1,68},
        # if_addr: {192,168,1,69},
        multicast_addr: {228,6,7,8},
        # a TTL of 1 remains on the local network,
        # use this to change the number of jumps the
        # multicast packets will make
        multicast_ttl: 1
      ],
      connect: {ClusterWork, :connect, []}
    ]
  ]
```

And I start two iex sessions:
```
$ iex --cookie foo --sname node1 -S mix
(edit config to use second if_addr)
$ iex --cookie foo --sname node2 -S mix
```

And they both just heartbeat but never connect.

Thanks for the help.

**Comment by bitwalker** [comment]
There definitely appears to be a problem with your connect implementation, namely `ClusterWork.connect(node)` isn't defined, at least that's why using the Epmd strategy raises on you. This function is called when there is a node to connect to, so until more than one node is present, no error will occur.

In the second case, I think you may need to bump the multicast TTL to at least 2, but if you could paste the output of the logs from both nodes with the log level set to `:debug`, I can figure out if there is something else going on there.

In my own testing, I use the Epmd strategy, primarily because I don't want to require devs on my team to ensure their machine has an extra IP for each node they want to spin up, and I'm not currently using the Gossip strategy in production (we're running under Kubernetes there). That said, you should certainly be able to use the Gossip strategy for local testing, so if it's not working, we need to fix it :)

**Comment by bitwalker** [comment]
Also, could you paste the output of `netstat -nr`?

**Comment by philipgiuliani** [comment]
I was just able to get the gossip adapter running with the default configuration locally! :)
But there actually seems to be a bug in the Adapter. See https://github.com/bitwalker/libcluster/pull/11

**Comment by bitwalker** [comment]
Great! I've merged your PR, thanks for tracking it down and contributing back! I'll close this for now, but feel free to reopen if you feel the issue is not yet resolved.

**Comment by cjbottaro** [comment]
I also encountered the bug @philipgiuliani reported, but I fixed it in my local dep of libcluster.  Thus it is not the cause of my troubles.

> There definitely appears to be a problem with your connect implementation, namely ClusterWork.connect(node) isn't defined, at least that's why using the Epmd strategy raises on you.

Yeah, that seems to be what the error indicates.  But something very strange is going on.  `ClusterWork.connect/1` _is_ defined.  In fact, when I start up the _first_ Erlang VM, everything is fine.  It's only when I start the second Erlang VM that it complains that `ClusterWork.connect/1` is not defined.

config.ex
```elixir
config :libcluster,
  topologies: [
    example: [
      strategy: Cluster.Strategy.Epmd,
      config: [hosts: [:"node1@haswell", :"node2@haswell"]],
      connect: {ClusterWork, :connect, []}
    ]
  ]
```

cluster_work.ex
```elixir
defmodule ClusterWork do

  def connect(name) do
    IO.puts "!!! ClusterWork.connect(#{inspect name}) !!!"
    :net_kernel.connect(name)
    true
  end

end
```

terminal 1
```
$ iex --cookie foo --sname node1 -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 1 file (.ex)
Generated cluster_work app
!!! ClusterWork.connect(:node1@haswell) !!!

10:33:44.528 [info]  [libcluster:example] connected to :node1@haswell
!!! ClusterWork.connect(:node2@haswell) !!!

10:33:44.577 [info]  [libcluster:example] connected to :node2@haswell
Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(node1@haswell)1>
```

terminal 2
```
$ iex --cookie foo --sname node2 -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]


=INFO REPORT==== 29-Dec-2016::10:34:55 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application libcluster: Cluster.App.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Strategy.Epmd
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Elixir.ClusterWork.connect/1 is undefined!
            (libcluster) lib/strategy/strategy.ex:34: anonymous fn/6 in Cluster.Strategy.connect_nodes/3
            (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
            (libcluster) lib/strategy/strategy.ex:30: Cluster.Strategy.connect_nodes/3
            (libcluster) lib/strategy/epmd.ex:26: Cluster.Strategy.Epmd.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
```

Any ideas?  Thanks!

**Comment by cjbottaro** [comment]
Continuing the discussion of the gossip strategy...

> could you paste the output of netstat -nr?

```
$ netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            10.10.10.1         UGSc          195        0     en0
10.10.10/24        link#4             UCS             8        0     en0
10.10.10.1/32      link#4             UCS             2        0     en0
10.10.10.1         80:2a:a8:8f:33:3d  UHLWIir       196       30     en0   1189
10.10.10.94        0:80:92:d6:93:74   UHLWIi          1        0     en0   1173
10.10.10.95        0:80:92:dc:3f:5c   UHLWIi          1        0     en0   1155
10.10.10.137       98:1:a7:e2:7d:43   UHLWIi          2        8     en0   1130
10.10.10.148/32    link#4             UCS             2        0     en0
10.10.10.148       60:f8:1d:b3:58:d8  UHLWIi          1        1     lo0
10.10.10.150       ac:bc:32:bf:da:77  UHLWIi          1        0     en0    454
10.10.10.187       74:e5:b:12:15:36   UHLWIi          1       20     en0   1198
10.10.10.255       link#4             UHLWbI          1      127     en0
127                127.0.0.1          UCS             1        0     lo0
127.0.0.1          127.0.0.1          UH             29  1714838     lo0
192.168.1          link#4             UCS             2        0     en0
192.168.1.69/32    link#4             UCS             1        0     en0
192.168.1.254/32   link#4             UCS             1        0     en0
192.168.1.255      link#4             UHLWbI          1      120     en0
224.0.0/4          link#4             UmCS            3        0     en0
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          1        0     en0
228.6.7.8/32       lo0                UmS             1      217     lo0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          1      128     en0
255.255.255.255/32 link#4             UCS             2        0     en0
255.255.255.255    link#4             UHLWbI          1      116     en0
```

I'm on my work's network now, so it's a bit different than I described before.

> I think you may need to bump the multicast TTL to at least 2

I tried that and it didn't change anything.

> if you could paste the output of the logs from both nodes with the log level set to :debug, I can figure out if there is something else going on there

config.ex
```elixir
config :libcluster,
  topologies: [
    gossip_example: [
      strategy: Cluster.Strategy.Gossip,
      config: [
        port: 45892,
        if_addr: {10,10,10,148},
        # if_addr: {192,168,1,69},
        multicast_addr: {228,6,7,8},
        # a TTL of 1 remains on the local network,
        # use this to change the number of jumps the
        # multicast packets will make
        multicast_ttl: 2
      ],
      connect: {ClusterWork, :connect, []}
    ]
  ]
```

terminal 1 (using {10,10,10,148})
```
$ iex --cookie foo --sname node1 -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 1 file (.ex)
Generated cluster_work app
Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)

10:43:25.583 [debug] [libcluster:gossip_example] heartbeat
iex(node1@haswell)1>
10:43:27.990 [debug] [libcluster:gossip_example] heartbeat

10:43:31.875 [debug] [libcluster:gossip_example] heartbeat

10:43:34.360 [debug] [libcluster:gossip_example] heartbeat
```

terminal 2 (using {192,168,1,69})
```
$ iex --cookie foo --sname node2 -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 1 file (.ex)
Generated cluster_work app
Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)

10:43:45.864 [debug] [libcluster:gossip_example] heartbeat
iex(node2@haswell)1>
10:43:46.841 [debug] [libcluster:gossip_example] heartbeat

10:43:51.138 [debug] [libcluster:gossip_example] heartbeat

10:43:54.385 [debug] [libcluster:gossip_example] heartbeat
```

Thanks for the help!

**Comment by girdharsojitra** [comment]
Even after restart both nodes one by one also it did not fix this issue.We also show below error:

> 2018-09-19 03:33:57.446 [info] pid=<0.2396.0> application=riak_core module=riak_core_gossip function=log_node_changed  'sms-core-cm@192.168.1.148' changed from 'valid' to 'leaving'^M
> 2018-09-19 03:33:57.811 [warn] pid=<0.2549.0> application=sms_routing module=SmsRouting.EntityManager function=handle_info/2  Could not get members of riak chashring: {:error, {:exit, {:noproc, {:gen_server, :call, [:riak_core_ring_manager, :get_raw_ring_chashbin, :infinity]}}}}^M
> 2018-09-19 03:33:57.814 [error] pid=<0.2549.0> application=sms_routing module=SmsRouting.EntityManager function=handle_info/2  Bad RPC joining riak cluster on node: :"sms-core-cm@192.168.1.148" for reason: {:EXIT, {:noproc, {:gen_server, :call, [:riak_core_ring_manager, :get_raw_ring, :infinity]}}}^M
> 2018-09-19 03:33:58.399 [warn] pid=<0.2549.0> application=sms_routing module=SmsRouting.EntityManager function=handle_info/2  Could not get members of riak chashring: {:error, {:exit, {:noproc, {:gen_server, :call, [:riak_core_ring_manager, :get_raw_ring_chashbin, :infinity]}}}}^M
> 2018-09-19 03:33:58.402 [error] pid=<0.2549.0> application=sms_routing module=SmsRouting.EntityManager function=handle_info/2  Bad RPC joining riak cluster on node: :"sms-core-cm@192.168.1.148" for reason: {:EXIT, {:noproc, {:gen_server, :call, [:riak_core_ring_manager, :get_raw_ring, :infinity]}}}^M
> 2018-09-19 03:34:02.079 [info] pid=<0.2722.0> application=sms_mo module=SmsMo function=prep_stop/1  Stopping the MO application...^M
> 2018-09-19 03:34:02.079 [info] pid=<0.2722.0> application=sms_mo module=SmsMo function=stop/1  Stopped the MO application.^M
